/* Aurora inverter status / alarm label tables (DSP response decode). */
#include "inverter_status_labels.h"
#include <stdio.h>

static const char *const k_global_states[102] = {
    "Sending Parameters",
    "Wait Sun/Grid",
    "Checking Grid",
    "Measuring Riso",
    "DcDc Start",
    "Inverter Turn-On",
    "Run",
    "Recovery",
    "Pause",
    "Ground Fault",
    "OTH Fault",
    "Address Setting",
    "Self Test",
    "Self Test Fail",
    "Sensor Test + Measure Riso",
    "Leak Fault",
    "Waiting for manual reset",
    "Internal Error E026",
    "Internal Error E027",
    "Internal Error E028",
    "Internal Error E029",
    "Internal Error E030",
    "Sending Wind Table",
    "Failed Sending Table",
    "UTH Fault",
    "Remote Off",
    "Interlock Fail",
    "Executing Autotest",
    NULL,
    NULL,
    "Waiting Sun",
    "Temperature Fault",
    "Fan Stuck",
    "Int. Com. Fail",
    "Slave Insertion",
    "DC Switch Open",
    "TRAS Switch Open",
    "MASTER Exclusion",
    "Auto Exclusion",
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    "Erasing Internal EEprom",
    "Erasing External EEprom",
    "Counting EEprom",
    "Freeze",
};
static const char *const k_inverter_states[48] = {
    "Stand By",
    "Checking Grid",
    "Run",
    "Bulk Over Voltage",
    "Out Over Current",
    "IGBT Sat",
    "Bulk Under Voltage",
    "Degauss Error",
    "No Parameters",
    "Bulk Low",
    "Grid Over Voltage",
    "Communication Error",
    "Degaussing",
    "Starting",
    "Bulk Cap Fail",
    "Leak Fail",
    "DcDc Fail",
    "I-leak Sensor Fail",
    "SelfTest: relay inverter",
    "SelfTest: wait for sensor test",
    "SelfTest: test relay DcDc + sensor",
    "SelfTest: relay inverter fail",
    "SelfTest: timeout fail",
    "SelfTest: relay DcDc fail",
    "Self Test 1",
    "Waiting self test start",
    "Dc Injection",
    "Self Test 2",
    "Self Test 3",
    "Self Test 4",
    "Internal Error (30)",
    "Internal Error (31)",
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    "Forbidden State",
    "Input UC",
    "Zero Power",
    "Grid Not Present",
    "Waiting Start",
    "MPPT",
    "Grid Fail",
    "Input OC",
};
static const char *const k_dcdc_states[20] = {
    "DcDc OFF",
    "Ramp Start",
    "MPPT",
    "not used",
    "Input Over Current",
    "Input Under Voltage",
    "Input Over Voltage",
    "Input Low",
    "No Parameters",
    "Bulk Over Voltage",
    "Communication Error",
    "Ramp Fail",
    "Internal Error",
    "Input mode Error",
    "Ground Fault",
    "Inverter Fail",
    "DcDc IGBT Sat",
    "DcDc ILEAK Fail",
    "DcDc Grid Fail",
    "DcDc Comm. Error",
};
static const char *const k_alarm_states[65] = {
    "No Alarm",
    "Sun Low W001 (1)",
    "Input Over Current E001",
    "Input Under Voltage W002",
    "Input Over Voltage E002",
    "Sun Low W001 (5)",
    "No Parameters E003",
    "Bulk Over Voltage E004",
    "Comm. Error E005",
    "Output Over Current E006",
    "IGBT Sat E007",
    "Sun Low - bulk undervoltage W011",
    "Internal error E009",
    "Grid Fail W003",
    "Bulk Low E010",
    "Ramp Fail E011",
    "Dc/Dc Fail E012",
    "Wrong Mode E013",
    "Ground Fault (18)",
    "Over Temp. E014",
    "Bulk Cap Fail E015",
    "Inverter Fail E016",
    "Start Timeout E017",
    "Ground Fault E018 (23)",
    "Degauss error (24)",
    "I-leak Sens. fail E019",
    "DcDc Fail E012",
    "Self  Test Error 1 E020",
    "Self  Test Error 2 E021",
    "Self  Test Error 3 E019",
    "Self  Test Error 4 E022",
    "DC inj error E023",
    "Grid Over Voltage W004",
    "Grid Under Voltage W005",
    "Grid OF W006",
    "Grid UF W007",
    "Z grid Hi W008",
    "Internal error E024",
    "Riso Low E025",
    "Vref Error E026",
    "Error Meas V E027",
    "Error Meas F E028",
    "Error Meas I E029",
    "Error Meas Ileak E030",
    "Read Error V E031",
    "Read Error I E032",
    "Table fail W009",
    "Fan Fail W010",
    "UTH E033",
    "Interlock Fail",
    "Remote Off",
    "Vout Avg error",
    "Battery low",
    "Clk fail",
    "Input UC",
    "Zero Power",
    "Fan Stuck",
    "DC Switch Open",
    "Tras Switch Open",
    "AC Switch Open",
    "Bulk UV",
    "Autoexclusion",
    "Grid df/dt",
    "Den switch Open",
    "Jbox fail",
};

static const char *lookup(const char *const *tab, int n, unsigned code, char *buf, size_t buflen)
{
    if (code >= (unsigned)n || tab[code] == NULL) {
        (void)snprintf(buf, buflen, "code %u", code);
        return buf;
    }
    return tab[code];
}

void aurora_decode_inverter_status(const uint8_t response[8], char *global, size_t glen,
                                   char *inverter, size_t ilen, char *chn1, size_t c1len,
                                   char *chn2, size_t c2len, char *alarm, size_t alen)
{
    if (response == NULL || global == NULL || inverter == NULL || chn1 == NULL || chn2 == NULL || alarm == NULL) {
        return;
    }
    if (response[1] == 0xffU) {
        const char *u = "Unavailable";
        (void)snprintf(global, glen, "%s", u);
        (void)snprintf(inverter, ilen, "%s", u);
        (void)snprintf(chn1, c1len, "%s", u);
        (void)snprintf(chn2, c2len, "%s", u);
        (void)snprintf(alarm, alen, "%s", u);
        return;
    }
    char b0[96], b1[96], b2[96], b3[96], b4[96];
    const char *pg = lookup(k_global_states, (int)(sizeof(k_global_states) / sizeof(k_global_states[0])), response[1], b0, sizeof(b0));
    const char *pi = lookup(k_inverter_states, (int)(sizeof(k_inverter_states) / sizeof(k_inverter_states[0])), response[2], b1, sizeof(b1));
    const char *p1 = lookup(k_dcdc_states, (int)(sizeof(k_dcdc_states) / sizeof(k_dcdc_states[0])), response[3], b2, sizeof(b2));
    const char *p2 = lookup(k_dcdc_states, (int)(sizeof(k_dcdc_states) / sizeof(k_dcdc_states[0])), response[4], b3, sizeof(b3));
    const char *pa = lookup(k_alarm_states, (int)(sizeof(k_alarm_states) / sizeof(k_alarm_states[0])), response[5], b4, sizeof(b4));
    (void)snprintf(global, glen, "%s", pg);
    (void)snprintf(inverter, ilen, "%s", pi);
    (void)snprintf(chn1, c1len, "%s", p1);
    (void)snprintf(chn2, c2len, "%s", p2);
    (void)snprintf(alarm, alen, "%s", pa);
}
